Module2 task1
htmlacademy-javascript/1897333-kekstagram-25 pull request #3
Opened 2022-02-21 15:04 UTC by shamozavr

добавлена функция для поиска случайного числа в заданном промежутке
добавлена функция для сравнения длины комментария с максимально допустимой

2022-02-21 20:17 UTC, blckwltz requested changes

2022-02-21 20:17 UTC, blckwltz commented on js/main.js
> +let randomNumber;
Не понятно, зачем нужна эта переменная. Можно возвращать значение из функции без нее.

2022-02-21 20:17 UTC, blckwltz commented on js/main.js
> +function between(min, max) {
`between` - не очень хорошее имя для функции. По нему нельзя понять, что эта функция делает, так же не соблюден [критерий Б6](https://up.htmlacademy.ru/javascript/25/criteries#b6). [Вот здесь](https://github.com/kettanaito/naming-cheatsheet) можно почитать о хороших именах для переменных.

2022-02-21 20:17 UTC, blckwltz commented on js/main.js
> +  if (min >= 0 && max >= 0) {
По заданию нужно также обрабатывать случай, когда `max` меньше чем `min`

2022-02-21 20:17 UTC, blckwltz commented on js/main.js
> +    console.log("min и max должны быть положительными числами");
По правилам `eslint` на курсе запрещено использовать `console` (вообще практически везде так, используется только во время разработки). Тут лучше [выбрасывать сообщение об ошибке](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/RangeError#example:_using_rangeerror). Еще стоит учитывать, что код после `return` в функциях не выполняется, поэтому ветку `else` тут можно не использовать

2022-02-21 20:17 UTC, blckwltz commented on js/main.js
> +function commentCheck(comment, maxLength) {
Тут с названием лучше, но все еще не совсем понятно, что именно проверяем.

2022-02-21 20:17 UTC, blckwltz commented on js/main.js
> +  }
Здесь можно все упростить до одной строки (подсказка: сравнение значений между собой само по себе выдает `true` или `false`) или как минимум убрать ветку `else`. Есть [вот такой критерий](https://up.htmlacademy.ru/javascript/25/criteries#d15) по этому поводу

2022-02-22 14:55 UTC, shamozavr commented on js/main.js
> +function between(min, max) {
заменил на getNumber

2022-02-22 14:55 UTC, shamozavr commented on js/main.js
> +let randomNumber;
убрал

2022-02-22 20:54 UTC, merged